language: node_js
os:
- linux
- osx
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
- lts/*
- stable
sudo: false

services:
  - mongodb
  - elasticsearch

env:
  - BULK_ACTION_TIMEOUT=30000 INDEXING_TIMEOUT=3000 CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_success:
  npm run coverage
