language: node_js
os:
- linux
- osx
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
- lts/*
- stable
sudo: false
dist: trusty
services:
  - mongodb
  - elasticsearch

env:
  - CC=gcc-4.8 CXX=g++-4.8

before_install:
- |
  if [[ ${TRAVIS_OS_NAME} == osx ]]; then
   export CXX=clang
   export CC=clang
  fi
- "$CC --version"
- "$CXX --version"
- env

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_success:
  npm run coverage
